version: '3.8'

services:
  app:
    build: .
    container_name: express_app
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
