services:
  app:
    build: .
    container_name: express_app
    restart: always
    ports:
      - '8080:8080' # For http
      - '8081:8081' # For ws
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
