version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.6.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_CLIENT_PORT}
      - ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME}
    ports:
      - '${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}'
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_ADVERTISED_LISTENER=${KAFKA_ADVERTISED_LISTENER}
      - KAFKA_LISTENER_SECURITY_PROTOCOL=${KAFKA_LISTENER_SECURITY_PROTOCOL}
      - KAFKA_LISTENER_PORT=${KAFKA_LISTENER_PORT}
      - KAFKA_LISTENER_NAME=${KAFKA_LISTENER_NAME}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_LISTENER_NAME_INSECURE=${KAFKA_LISTENER_NAME_INSECURE}
      - KAFKA_LISTENER_PORT_INSECURE=${KAFKA_LISTENER_PORT_INSECURE}
    ports:
      - '${KAFKA_LISTENER_PORT}:${KAFKA_LISTENER_PORT}'
    depends_on:
      - zookeeper
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
