version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '${PGADMIN_PORT}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
      PGADMIN_LISTEN_PORT: '80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pg_network

volumes:
  pgadmin-data:

networks:
  pg_network:
