services:
  postgres_local:
    image: postgres:latest
    container_name: postgres_local
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis_local:
    image: redis:latest
    container_name: redis_local
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
