services:
  express_app_prod:
    container_name: express_app_prod
    build:
      context: .
      dockerfile: dockerfile
    image: express_app_prod:latest
    ports:
      - '${APP_PORT}:${APP_PORT}'
    env_file:
      - .env
