services:
  prisma-studio:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npx prisma studio"
    ports:
      - '${PRISMA_PORT}:${PRISMA_PORT}'
    env_file:
      - .env
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:8
    env_file:
      - .env
    ports:
      - '${PGADMIN_PORT}:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgadmin_data:
