services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - '${PGADMIN_PORT}:${PGADMIN_PORT}'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network_prod

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-studio
    restart: always
    ports:
      - '${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}'
    command: npx prisma studio
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app_network_prod

volumes:
  pgadmin_data:

networks:
  app_network_prod:
